version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password

  website:
    depends_on:
      - postgres
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  postgres:
