
# default docker
default: &default
  adapter: postgresql
  timeout: 5000
  encoding: unicode
  host: postgres
  username: postgres
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  password: password

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: healthapp_development

test:
  <<: *default
  database: healthapp_test

production:
  <<: *default
  database: healthapp_production
  username: healthapp
  password: <%= ENV['HEALTHAPP_DATABASE_PASSWORD'] %>
